using InstituteHub.Application.Abstractions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace InstituteHub.Infrastructure.Storage;

/// <summary>"Storage" section. LocalRoot is relative to the app folder unless absolute (Docker: /app/data).</summary>
public sealed class StorageOptions
{
    public const string SectionName = "Storage";
    public string LocalRoot { get; set; } = "App_Data/files";
}

/// <summary>Files on the server's disk (a Docker volume in production; include it in backups).</summary>
public sealed class LocalFileStorage(IOptions<StorageOptions> options, IHostEnvironment environment) : IFileStorage
{
    private readonly string _root = Path.GetFullPath(
        Path.IsPathRooted(options.Value.LocalRoot)
            ? options.Value.LocalRoot
            : Path.Combine(environment.ContentRootPath, options.Value.LocalRoot));

    public async Task<string> SaveAsync(string key, Stream content, CancellationToken ct = default)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
        await content.CopyToAsync(file, ct);
        return key;
    }

    public async Task<byte[]?> ReadAsync(string key, CancellationToken ct = default)
    {
        var path = PathFor(key);
        return File.Exists(path) ? await File.ReadAllBytesAsync(path, ct) : null;
    }

    public Task DeleteAsync(string key, CancellationToken ct = default)
    {
        var path = PathFor(key);
        if (File.Exists(path)) File.Delete(path);
        return Task.CompletedTask;
    }

    /// <summary>Keys are generated by the app, but never allow one to point outside the storage root.</summary>
    private string PathFor(string key)
    {
        var path = Path.GetFullPath(Path.Combine(_root, key.Replace('\\', '/').TrimStart('/')));
        if (!path.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            throw new InvalidOperationException("Invalid storage key.");
        return path;
    }
}
